// app/blog/page.tsx
import React from "react";
import Header from "@/app/Header";
import PostList from "@/app/blog/PostList";
import BannerLinks from "@/components/BannerLinks";

const Blog = () => {
  return (
    <>
      <Header title="self*-awarded" subtitle="award-winning blog" />
      {/* @ts-expect-error Async Server Component */}
      <PostList />
      <BannerLinks />
    </>
  );
};

export default Blog;

// src/routes/blog/+page.svelte
<script lang="ts">
  import Header from "$lib/components/Header.svelte";
  import BannerLinks from "$lib/components/BannerLinks.svelte";

  import type { PageServerData } from "./$types";
  import PostList from "$lib/components/PostList.svelte";

  export let data: PageServerData;
</script>

<main class="grid gap-4 grid-flow-row bg-black p-4 min-h-screen">
  <Header subtitle="award-winning blog" title="brain juice" />
  <PostList posts={data.posts} />
  <BannerLinks />
</main>
