// src/components/Profile.svelte
<div class="mx-auto max-w-[1000px] flex flex-col md:flex-row items-center w-full">
  <img
    alt="Picture of Zachary Corvidae, owner of Sneaky Crow"
    class="rounded-full inline-block my-4 self-center"
    height={200}
    src="/profile_normal.jpeg"
    width={200}
  />
  <ul class="inline-flex flex-col md:ml-10 text-base md:text-lg justify-center items-start">
    <li>
      <span class="font-bold">Name:</span> Zachary Corvidae
    </li>
    <li>
      <span class="font-bold">Class:</span> Software Engineer
    </li>
    <li>
      <span class="font-bold">Origin:</span> Portland, OR
    </li>
    <li>
      <span class="font-bold">Experience:</span> 20
      <span class="font-light text-sm md:text-base"> (years)</span>
    </li>
  </ul>
</div>

// web/components/Profile.tsx
const Profile = () => {
  return (
    <div className="flex flex-col md:flex-row justify-evenly items-center p-6">
      <img
        src="/profile_normal.jpeg"
        alt="Picture of Zachary Sohovich, owner of Sneaky Crow"
        height="658"
        width="658"
        className="rounded-full inline-block w-1/3"
      />
      <ul className="inline-block">
        <li>
          <span className="font-bold">Name:</span> Zachary Sohovich
        </li>
        <li>
          <span className="font-bold">Class:</span> Software Engineer
        </li>
        <li>
          <span className="font-bold">Origin:</span> Portland, OR
        </li>
        <li>
          <span className="font-bold">Experience:</span> 20
          <span className="font-light text-xs"> (years)</span>
        </li>
      </ul>
    </div>
  );
};

export default Profile;
