// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
  import Hero from "../../../components/Hero.svelte";
  import Article from "../../../components/Article.svelte";
  import BannerLinks from "../../../components/BannerLinks.svelte";
  import type { PageServerData } from "./$types";

  export let data: PageServerData;
</script>

<main class="flex flex-col gap-4 bg-black p-4">
  <header>
    <Hero homeURL="/blog" subtitle="" title={data.post.title} />
  </header>
  <Article post={data.post} />
  <BannerLinks />
</main>

// web/app/blog/[...slug]/page.tsx
import React from "react";
import Hero from "@/components/Hero";

interface BlogPageProps {
  params: {
    slug: string[];
  };
}

const BlogPage = (props: BlogPageProps) => {
  return (
    <>
      <header className="col-span-2">
        <Hero title={props.params.slug.join("-")} subtitle="" />
      </header>
      <article className="min-h-[75vh] bg-white col-span-2"></article>
    </>
  );
};

export default BlogPage;
