// src/components/Header.svelte
<script lang="ts">
  import Hero from "./Hero.svelte";
  import Navigation from "./Navigation.svelte";

  export let title: string;
  export let subtitle: string;
</script>

<header class="xl:max-h-[50vh] w-full grid grid-flow-row xl:grid-flow-col">
  <Hero {subtitle} {title} />
  <Navigation />
</header>

// app/Header.tsx
import Hero from "@/components/Hero";
import Navigation from "@/components/Navigation";

interface HeaderProps {
  title?: string;
  subtitle?: string;
}

const Header = (props: HeaderProps) => (
  <header className="max-h-[50vh] w-full grid grid-flow-row xl:grid-flow-col">
    <Hero title={props.title} subtitle={props.subtitle} />
    <Navigation />
  </header>
);

export default Header;
