// src-legacy/lib/components/Profile.svelte
<script lang="ts">
  import { titles } from "$lib";
  import BlurTextList from "./BlurTextList.svelte";
  interface Props {
    [key: string]: any
  }

  let { ...rest }: Props = $props();
</script>

<div
  class={`grid lg:grid-cols-4 gap-8 items-center lg:items-start justify-center lg:justify-start w-full ${rest.class}`}
>
  <img
    alt="Zachary Corvidae, owner of Sneaky Crow"
    class="rounded-md border-primary-500 shadow-md mx-auto"
    width={150}
    height={150}
    src="/profile_normal.jpeg"
  />
  <aside class="lg:col-start-2 lg:col-span-3 w-full text-center lg:text-left">
    <h2 class="text-xl lg:text-2xl mb-4 font-semibold">Zachary Corvidae</h2>
    <BlurTextList textList={titles} />
  </aside>
</div>

// components/Profile.tsx
import Image from "next/image";

const Profile = () => {
  return (
    <div className="mx-auto max-w-[1000px] flex flex-col md:flex-row md:items-center w-full">
      <Image
        src="/profile_normal.jpeg"
        alt="Picture of Zachary Corvidae, owner of Sneaky Crow"
        height="200"
        width="200"
        className="rounded-full inline-block my-4 self-center"
      />
      <ul className="inline-flex flex-col md:ml-10 text-base md:text-lg justify-center items-start">
        <li>
          <span className="font-bold">Name:</span> Zachary Corvidae
        </li>
        <li>
          <span className="font-bold">Class:</span> Software Engineer
        </li>
        <li>
          <span className="font-bold">Origin:</span> Portland, OR
        </li>
        <li>
          <span className="font-bold">Experience:</span> 20
          <span className="font-light text-sm md:text-base"> (years)</span>
        </li>
      </ul>
    </div>
  );
};

export default Profile;
