// src/lib/components/PostList.svelte
<script lang="ts">
  import PostExcerpt from "$lib/components/post/PostExcerpt.svelte";
  import type { Post } from "$lib/posts";

  export let posts: Post[];
</script>

<div class={`flex flex-col space-y-8 w-full ${$$restProps.class}`}>
  {#each posts as post}
    <PostExcerpt {post} />
  {/each}
</div>

// web/app/blog/PostList.tsx
import { getPosts, ShortPost } from "@/components/Post";

const PostList = async () => {
  const posts = await getPosts();
  return (
    <div className="flex flex-col w-full bg-white">
      {posts.map((post) => (
        <ShortPost key={post.id} short post={post} />
      ))}
    </div>
  );
};

export default PostList;
