// web/components/Hero/index.tsx
import Image from "next/image";
import React from "react";
import Link from "next/link";
import "./Hero.css";

interface HeroProps {
  imageURL?: string;
  title?: string;
  subtitle?: string;
}

const Index = (props: HeroProps) => {
  const {
    imageURL = "/logo_v2.svg",
    title = "Sneaky Crow",
    subtitle = "software wizard ",
  } = props;
  return (
    <div className="p-6 bg-white grid grid-flow-row lg:grid-flow-col">
      <Link href="/" className="inline-flex justify-center min-w-3/4">
        <Image alt="" src={imageURL} width={200} height={200} />
      </Link>
      <div className="flex flex-col justify-center items-center lg:items-start font-extrabold">
        <h1 className="title">{title}</h1>
        <h2 className="text-2xl leading-13">{subtitle}</h2>
      </div>
    </div>
  );
};

export default Index;

// src/components/Hero.svelte
<script lang="ts">
  export let homeURL: string = "/";
  export let title: string;
  export let subtitle: string;
</script>

<div class="bg-white grid grid-flow-row md:grid-flow-col justify-center">
  <a class="inline-flex justify-self-center md:justify-self-end min-w-3/4" href={homeURL}>
    <img
      alt="Line art of a crow with a green baseball cap on, logo of Sneaky Crow"
      class="min-w-[200px]"
      height={200}
      src="/logo_v2.svg"
      width={200}
    />
  </a>
  <div class="flex flex-col justify-center items-center font-extrabold">
    <h1 class="w-full text-lg lg:text-2xl text-center lg:text-left">
      {title}
    </h1>
    <h2 class="w-full text-xl leading-13 text-center lg:text-left">
      {subtitle}
    </h2>
  </div>
</div>
