// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
  import Article from "../../../components/Article.svelte";
  import BannerLinks from "../../../components/BannerLinks.svelte";
  import type { PageServerData } from "./$types";
  import Title from "../../../components/Title.svelte";
  import Header from "../../../components/Header.svelte";

  export let data: PageServerData;
</script>

<main class="flex flex-col gap-4 bg-black p-4">
  <Header subtitle="" title={data.post.title} />
  <Article post={data.post} />
  {#if data.series?.length ?? [] > 0}
    <div class="w-full bg-white flex flex-col items-center justify-center">
      <div class="py-2 max-w-[1000px] w-full">
        <Title>Series</Title>
        <ol
          class="list-decimal list-inside grid grid-flow-row items-center space-y-2 text-lg">
          {#each data.series as post}
            <li class={`${post.slug === data.post.slug ? "text-green-550 opacity-60" : "text-green-550"}`}>
              <a href={`/blog/${post.slug}`}>{post.title}</a>
            </li>
          {/each}
        </ol>
      </div>
    </div>
  {/if}
  <BannerLinks />
</main>

// pages/blog/[...slug].tsx
import React from "react";
import Hero from "@/components/Hero";
import { BlogPost, getPostBySlug, getPosts } from "@/components/Post";
import Markdown from "@/components/Markdown";
import "@/app/globals.css";
import Head from "next/head";

const BlogPage = (props: BlogPost) => {
  const { title, body } = props;
  return (
    <>
      <Head>
        <title>{title}</title>
      </Head>
      <main className="grid gap-4 grid-flow-row bg-black p-4 min-h-screen">
        <header className="col-span-2">
          <Hero title={title} subtitle="" />
        </header>
        <article className="min-h-[75vh] bg-white col-span-2 p-6 flex justify-center">
          <Markdown>{body}</Markdown>
        </article>
      </main>
    </>
  );
};

// @ts-ignore
export async function getStaticProps(context) {
  return {
    props: await getPostBySlug(context.params.slug),
  };
}

export async function getStaticPaths() {
  const posts = await getPosts();
  const paths = posts.map((post) => post.slug);

  return {
    paths: paths,
    fallback: false,
  };
}

export default BlogPage;
