// components/Footer.tsx
import Link from "next/link";

const subnavLinks: { url: string; copy: string; rel?: string }[] = [
  {
    copy: "github",
    url: "https://github.com/sneakycrow",
  },
  {
    copy: "resume",
    url: "/resume.pdf",
  },
  {
    copy: "mastadon",
    url: "https://cybre.gg/@ctrlsquid",
    rel: "me",
  },
];

const Footer = () => {
  return (
    <footer className="bg-gray-100 p-4 w-full flex flex-col justify-evenly xl:flex-row items-center">
      {subnavLinks.map((link) => (
        <Link
          href={link.url}
          {...link}
          className="text-2xl font-bold text-green-550 opacity-75 hover:opacity-100 transition-opacity"
        >
          {link.copy}
        </Link>
      ))}
    </footer>
  );
};

export default Footer;

// src/lib/components/Footer.svelte
<script lang="ts">
  import AvatarWidget from "./AvatarWidget.svelte";
  import GitHub from "./icons/GitHub.svelte";

  type User = {
    username: string;
    avatar: string;
    role?: string;
  };
  export let user: User | null = null;
  const links = [{ copy: "settings", url: "/settings" }];
</script>

<footer
  class={`py-4 flex flex-col space-y-10 lg:flex-row justify-between items-center z-10 ${$$restProps.class}`}
>
  <p class="flex flex-col">
    <span class="text-sm">© {new Date().getFullYear()} Sneaky Crow, LLC</span>
    <span class="text-sm">All Rights Reserved</span>
    <a
      class="text-gray-500 font-normal flex items-center space-x-2"
      href="https://github.com/sneakycrow/website"
    >
      <span>source code for this site</span>
      <GitHub class="inline-block w-4 h-4" />
    </a>
    <a href="mailto:zach@sneakycrow.dev">contact me</a>
  </p>
  {#if user}
    <AvatarWidget {user} {links} />
  {:else}
    <a href="/login">Login</a>
  {/if}
</footer>
