// app/blog/PostList.tsx
import { getPosts, ShortPost } from "@/components/Post";
import Title from "@/components/Title";

const PostList = async () => {
  const posts = await getPosts();
  return (
    <div className="flex flex-col w-full bg-white p-6 lg:items-center">
      <Title className="lg:w-3/4 max-w-[1000px]">Posts</Title>
      <div className="lg:w-3/4 max-w-[1000px] divide-y-2">
        {posts.map((post) => (
          <ShortPost key={post.id} post={post} />
        ))}
      </div>
    </div>
  );
};

export default PostList;

// src/lib/components/PostList.svelte
<script lang="ts">
  import PostExcerpt from "$lib/components/PostExcerpt.svelte";
  import Title from "$lib/components/Title.svelte";
  import type { Post } from "$lib/posts";

  export let posts: Post[];
  export let title = "Posts";
  export let cols = "grid-cols-1";
</script>

<div class="flex flex-col w-full bg-white p-6 lg:items-center">
  <div class="lg:w-3/4 max-w-[1000px]">
    <Title>{title}</Title>
    <div class={`divide-green-100 grid ${cols}`}>
      {#each posts as post, i}
        <PostExcerpt {post} />
      {/each}
    </div>
  </div>
</div>
