// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
  import Hero from "../../../components/Hero.svelte";
  import Article from "../../../components/Article.svelte";
  import BannerLinks from "../../../components/BannerLinks.svelte";
  import type { PageServerData } from "./$types";

  export let data: PageServerData;
</script>

<main class="flex flex-col gap-4 bg-black p-4">
  <header>
    <Hero homeURL="/blog" subtitle="" title={data.post.title} />
  </header>
  <Article post={data.post} />
  <BannerLinks />
</main>

// app/blog/[...slug]/page.tsx
import React from "react";
import Hero from "@/components/Hero";
import { getPostBySlug } from "@/components/Post";
import Markdown from "@/components/Markdown";

interface BlogPageProps {
  params: {
    slug: string[];
  };
}

const BlogPage = async (props: BlogPageProps) => {
  const data = await getPostBySlug(props.params.slug[0]);
  return (
    <>
      <header className="col-span-2">
        <Hero title={data.title} subtitle="" />
      </header>
      <article className="min-h-[75vh] bg-white col-span-2 p-6 leading-loose flex justify-center">
        <Markdown>{data.body}</Markdown>
      </article>
    </>
  );
};

export default BlogPage;
